# Generated by Django 4.0.6 on 2022-12-31 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Alert List',
                'verbose_name_plural': 'Alert Lists',
            },
        ),
        migrations.CreateModel(
            name='counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counties', models.CharField(max_length=25)),
                ('codes', models.IntegerField()),
                ('cty_code', models.CharField(max_length=24)),
                ('dis', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(default=None, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'counties',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('Resolue', models.BooleanField()),
                ('Encours', models.BooleanField()),
                ('attachment', models.FileField(null=True, upload_to='public')),
                ('private_file', private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='private')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformationSystem.alertlist')),
            ],
        ),
    ]
