# Generated by Django 4.0.6 on 2022-12-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': 'Counties'},
        ),
    ]
