# Generated by Django 4.0.6 on 2023-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
