# Generated by Django 4.0.6 on 2023-04-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0003_alter_alert_encours_alter_alert_resolue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='autor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
