# Generated by Django 4.0.6 on 2023-04-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0004_alter_alert_autor_alter_alert_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
