# Generated by Django 4.0.6 on 2023-04-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0006_alter_alert_encours_alter_alert_resolue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
