# Generated by Django 4.0.6 on 2023-04-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0008_alter_alert_title_alter_alertlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='export_to_CSV',
        ),
    ]
