# Generated by Django 4.0.6 on 2023-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0010_alter_alert_encours_alter_alert_resolue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
