# Generated by Django 4.0.6 on 2023-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0011_alert_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='number_alerts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='receive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='receive_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
