# Generated by Django 4.0.6 on 2023-04-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0012_alert_number_alerts_alert_receive_alert_receive_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
