# Generated by Django 4.0.6 on 2023-04-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0013_alter_alert_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='private_file',
        ),
    ]
