# Generated by Django 4.0.6 on 2023-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformationSystem', '0014_remove_alert_attachment_remove_alert_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='latitude',
        ),
        migrations.AddField(
            model_name='alert',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
